apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kaoftj2gm-nodejs 
  janus-idp.io/tekton: kaoftj2gm-nodejs
  backstage.io/kubernetes-id: kaoftj2gm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kaoftj2gm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  