apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kaoftj2gm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kaoftj2gm-nodejs 
  name: kaoftj2gm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kaoftj2gm-nodejs 
